---
- name: "Backup Huawei via AWX"
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.network.vrp
    ansible_connection: ansible.netcommon.network_cli
    ansible_port: 23
  collections:
    - ansible.netcommon
    - community.network
  tasks:
    - name: "Deshabilitar paginacion"
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary

    - name: "Obtener configuracion actual del switch"
      ansible.netcommon.cli_command:
        command: display current-configuration
      register: backup_raw

    - name: "Mostrar el backup en el log de AWX"
      debug:
        msg: "{{ backup_raw.stdout }}"
