---
- name: "Sincronizar NetBox a Zabbix"
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: "Crear Host en Zabbix"
      community.zabbix.zabbix_host:
        # URL con la ruta /zabbix incluida
        server_url: "http://10.0.0.23/zabbix/api_jsonrpc.php"
        http_login_password: "{{ zabbix_api_token }}"
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        status: enabled
        interfaces:
          - type: 2
            main: 1
            useip: 1
            ip: "{{ ansible_host }}"
            port: "161"
        host_groups:
          - "Switches Uruguay"
        link_templates:
          - "Huawei CloudEngine SNMP"
      delegate_to: localhost
      when: ansible_host is defined
